language: cpp

os:
  - linux

compiler:
  - g++

before_install:
  - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
  - sudo apt-get update -qq

install:
  - sudo apt-get install -qq gcc-4.9 g++-4.9
  - export CXX="g++-4.9"

script:
  - sh maker.sh
